from __future__ import annotations

from pathlib import Path

import map_path_planner
from waypoint_following.command_smoothing import COMMAND_SMOOTHING_RATE_LIMIT
from waypoint_following.controllers import (
    FORWARD_CONTROL_TARGET_BEARING,
    PATH_PROFILE_SCHEDULING_OFF,
)
from waypoint_following.lookahead_guard import LOOKAHEAD_GUARD_OFF
from waypoint_following.velocity_scheduler import SPEED_PROFILE_FIXED


__all__ = (
    "DEFAULT_WAYPOINTS_CSV",
    "DEFAULT_RESULTS_CSV",
    "DEFAULT_STATIC_MAP",
    "DEFAULT_REPLAN_OUTPUT_DIR",
    "DEFAULT_RVIZ_PATH_TOPIC",
    "DEFAULT_RVIZ_WAYPOINT_MARKER_TOPIC",
    "DEFAULT_RVIZ_OBSTACLE_MARKER_TOPIC",
    "DEFAULT_LINEAR_SPEED_MPS",
    "DEFAULT_PURE_PURSUIT_LINEAR_SPEED_MPS",
    "DEFAULT_MIN_LINEAR_SPEED_MPS",
    "DEFAULT_LINEAR_GAIN",
    "DEFAULT_MAX_ANGULAR_SPEED_RADPS",
    "DEFAULT_PURE_PURSUIT_MAX_ANGULAR_SPEED_RADPS",
    "DEFAULT_YAW_GAIN",
    "DEFAULT_WAYPOINT_TOLERANCE_M",
    "DEFAULT_GOAL_TOLERANCE_M",
    "DEFAULT_ROTATE_START_HEADING_ERROR_DEG",
    "DEFAULT_ROTATE_STOP_HEADING_ERROR_DEG",
    "DEFAULT_FORWARD_YAW_DEADBAND_DEG",
    "DEFAULT_FORWARD_STOP_HEADING_ERROR_DEG",
    "DEFAULT_MIN_WAYPOINT_SPACING_M",
    "DEFAULT_START_SELECTION",
    "DEFAULT_START_ON_PATH_TOLERANCE_M",
    "DEFAULT_CONTROLLER",
    "DEFAULT_PATH_LOOKAHEAD_M",
    "DEFAULT_PURE_PURSUIT_LOOKAHEAD_GUARD",
    "DEFAULT_PURE_PURSUIT_MIN_GUARDED_LOOKAHEAD_M",
    "DEFAULT_PURE_PURSUIT_LOOKAHEAD_GUARD_STATIC_INFLATION_RADIUS_M",
    "DEFAULT_PURE_PURSUIT_COMMAND_SMOOTHING",
    "DEFAULT_PURE_PURSUIT_MAX_LINEAR_ACCEL_MPS2",
    "DEFAULT_PURE_PURSUIT_MAX_LINEAR_DECEL_MPS2",
    "DEFAULT_PURE_PURSUIT_MAX_ANGULAR_ACCEL_RADPS2",
    "DEFAULT_PURE_PURSUIT_MAX_ANGULAR_DECEL_RADPS2",
    "DEFAULT_PURE_PURSUIT_FINAL_DECEL_DISTANCE_M",
    "DEFAULT_PURE_PURSUIT_SPEED_PROFILE",
    "DEFAULT_PURE_PURSUIT_FORWARD_CONTROL",
    "DEFAULT_PURE_PURSUIT_PATH_PROFILE_SCHEDULING",
    "DEFAULT_PURE_PURSUIT_PATH_PROFILE_STRAIGHT_SPEED_MPS",
    "DEFAULT_PURE_PURSUIT_ROUTE_HEADING_BLEND",
    "DEFAULT_PURE_PURSUIT_CROSS_TRACK_GAIN",
    "DEFAULT_PURE_PURSUIT_CROSS_TRACK_SPEED_FLOOR_MPS",
    "DEFAULT_PURE_PURSUIT_MAX_CROSS_TRACK_CORRECTION_DEG",
    "DEFAULT_PURE_PURSUIT_ANGULAR_FEASIBILITY_SPEED_LIMIT",
    "DEFAULT_PURE_PURSUIT_ANGULAR_FEASIBILITY_MARGIN",
    "DEFAULT_PURE_PURSUIT_MAX_LATERAL_ACCEL_MPS2",
    "DEFAULT_PURE_PURSUIT_TURN_SPEED_MARGIN",
    "DEFAULT_PURE_PURSUIT_ROTATE_START_HEADING_ERROR_DEG",
    "DEFAULT_PURE_PURSUIT_ROTATE_STOP_HEADING_ERROR_DEG",
    "DEFAULT_PURE_PURSUIT_ROUTE_HEADING_ROTATE_START_DEG",
    "DEFAULT_PURE_PURSUIT_ROUTE_HEADING_ROTATE_STOP_DEG",
    "DEFAULT_PURE_PURSUIT_MAX_TRACK_ANGULAR_SPEED_RADPS",
    "DEFAULT_PURE_PURSUIT_HEADING_DEADBAND_DEG",
    "DEFAULT_PURE_PURSUIT_LATERAL_DEADBAND_M",
    "DEFAULT_PURE_PURSUIT_CURVATURE_LIMIT_START_HEADING_ERROR_DEG",
    "DEFAULT_PURE_PURSUIT_CURVATURE_LIMIT_FULL_HEADING_ERROR_DEG",
    "DEFAULT_PURE_PURSUIT_CROSS_TRACK_WARNING_M",
    "DEFAULT_PURE_PURSUIT_MAX_CROSS_TRACK_ERROR_M",
    "DEFAULT_TRACKING_ENDPOINT_TOLERANCE_M",
    "DEFAULT_TRACKING_START_TOLERANCE_M",
    "DEFAULT_TRACKING_MAX_SEGMENT_M",
    "DEFAULT_ODOM_FRAME",
    "DEFAULT_SCAN_HALF_ANGLE_DEG",
    "DEFAULT_HARD_STOP_RANGE_M",
    "DEFAULT_MIN_SCAN_RANGE_M",
    "DEFAULT_ROTATION_STOP_RANGE_M",
    "FORWARD_SOFT_STOP_MIN_CLOSE_RANGES",
    "DEFAULT_MAX_POSE_AGE_SEC",
    "DEFAULT_MAX_SCAN_AGE_SEC",
    "DEFAULT_MAX_AMCL_AGE_SEC",
    "DEFAULT_MAX_AMCL_VAR_X",
    "DEFAULT_MAX_AMCL_VAR_Y",
    "DEFAULT_MAX_AMCL_VAR_YAW",
    "DEFAULT_MAX_WAYPOINT_TIME_SEC",
    "DEFAULT_MAX_TF_UPDATE_GAP_SEC",
    "DEFAULT_TF_RECOVERY_TIME_SEC",
    "DEFAULT_LOCALIZATION_RECOVERY_TIME_SEC",
    "DEFAULT_CONTROL_RATE_HZ",
    "DEFAULT_SETTLE_SEC",
    "DEFAULT_REPLAN_TIMEOUT_SEC",
    "DEFAULT_MAX_REPLAN_SCAN_AGE_SEC",
    "DEFAULT_MAX_REPLAN_TF_AGE_SEC",
    "DEFAULT_OBSTACLE_FORWARD_DISTANCE_M",
    "DEFAULT_OBSTACLE_FORWARD_HALF_WIDTH_M",
    "DEFAULT_OBSTACLE_ANGLE_WINDOW_DEG",
    "DEFAULT_OBSTACLE_MIN_RANGE_M",
    "DEFAULT_ROBOT_FOOTPRINT_RADIUS_M",
    "DEFAULT_OBSTACLE_MIN_CLUSTER_SIZE",
    "DEFAULT_OBSTACLE_MIN_CLUSTER_WIDTH_M",
    "DEFAULT_OBSTACLE_INFLATE_RADIUS_M",
    "DEFAULT_MAX_START_SNAP_M",
    "DEFAULT_MAX_GOAL_SNAP_M",
    "DEFAULT_MAX_REPLAN_PATH_LENGTH_RATIO",
    "DEFAULT_RUN_LOCAL_MAP_INITIAL_SCAN_MODE",
    "DEFAULT_RUN_LOCAL_MAP_INITIAL_SCAN_COUNT",
    "DEFAULT_RUN_LOCAL_MAP_UPDATE_MODE",
    "DEFAULT_RUN_LOCAL_MAP_MIN_HIT_COUNT",
    "DEFAULT_RUN_LOCAL_MAP_INFLATION_RADIUS_M",
    "DEFAULT_RUN_LOCAL_MAP_MAX_TF_AGE_SEC",
    "DEFAULT_RUN_LOCAL_MAP_MAX_SCAN_AGE_SEC",
    "DEFAULT_RUN_LOCAL_MAP_MIN_USED_POINTS",
    "DEFAULT_RUN_LOCAL_MAP_MAX_REJECTED_RATIO",
    "DEFAULT_RUN_LOCAL_MAP_CORRIDOR_CHECK_DISTANCE_M",
    "DEFAULT_RUN_LOCAL_MAP_CLEARANCE_MARGIN_M",
    "DEFAULT_RUN_LOCAL_MAP_MAX_UPDATES",
    "DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_COUNT",
    "DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_FORWARD_HALF_WIDTH_M",
    "DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_ANGLE_WINDOW_DEG",
    "DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_FORWARD_DISTANCE_M",
    "DEFAULT_RUN_LOCAL_MAP_PRUNE_BEHIND_DISTANCE_M",
    "DEFAULT_STARTUP_TIMEOUT_SEC",
    "STOP_PUBLISH_COUNT",
    "STOP_PUBLISH_HZ",
)


DEFAULT_WAYPOINTS_CSV = Path("results/aufgabe03/aufgabe03_waypoints.csv")
DEFAULT_RESULTS_CSV = Path("results/aufgabe03/aufgabe03_waypoint_follow_runs.csv")
DEFAULT_STATIC_MAP = Path("maps/aufgabe03/arena_1p898x3p9_auto.yaml")
DEFAULT_REPLAN_OUTPUT_DIR = Path("results/aufgabe03")
DEFAULT_RVIZ_PATH_TOPIC = "/mii_amr/planned_path"
DEFAULT_RVIZ_WAYPOINT_MARKER_TOPIC = "/mii_amr/planned_waypoints"
DEFAULT_RVIZ_OBSTACLE_MARKER_TOPIC = "/mii_amr/run_local_obstacles"

DEFAULT_LINEAR_SPEED_MPS = 0.04
DEFAULT_PURE_PURSUIT_LINEAR_SPEED_MPS = 0.06
DEFAULT_MIN_LINEAR_SPEED_MPS = 0.012
DEFAULT_LINEAR_GAIN = 0.25
DEFAULT_MAX_ANGULAR_SPEED_RADPS = 0.09
DEFAULT_PURE_PURSUIT_MAX_ANGULAR_SPEED_RADPS = 0.20
DEFAULT_YAW_GAIN = 0.35
DEFAULT_WAYPOINT_TOLERANCE_M = 0.12
DEFAULT_GOAL_TOLERANCE_M = 0.12
DEFAULT_ROTATE_START_HEADING_ERROR_DEG = 20.0
DEFAULT_ROTATE_STOP_HEADING_ERROR_DEG = 7.0
DEFAULT_FORWARD_YAW_DEADBAND_DEG = 3.0
DEFAULT_FORWARD_STOP_HEADING_ERROR_DEG = 18.0
DEFAULT_MIN_WAYPOINT_SPACING_M = 0.12
DEFAULT_START_SELECTION = "path-progress"
DEFAULT_START_ON_PATH_TOLERANCE_M = 0.25
DEFAULT_CONTROLLER = "stop-go"
DEFAULT_PATH_LOOKAHEAD_M = 0.18
DEFAULT_PURE_PURSUIT_LOOKAHEAD_GUARD = LOOKAHEAD_GUARD_OFF
DEFAULT_PURE_PURSUIT_MIN_GUARDED_LOOKAHEAD_M = 0.12
DEFAULT_PURE_PURSUIT_LOOKAHEAD_GUARD_STATIC_INFLATION_RADIUS_M = (
    map_path_planner.DEFAULT_INFLATE_RADIUS_M
)
DEFAULT_PURE_PURSUIT_COMMAND_SMOOTHING = COMMAND_SMOOTHING_RATE_LIMIT
DEFAULT_PURE_PURSUIT_MAX_LINEAR_ACCEL_MPS2 = 0.06
DEFAULT_PURE_PURSUIT_MAX_LINEAR_DECEL_MPS2 = 0.12
DEFAULT_PURE_PURSUIT_MAX_ANGULAR_ACCEL_RADPS2 = 0.18
DEFAULT_PURE_PURSUIT_MAX_ANGULAR_DECEL_RADPS2 = 0.36
DEFAULT_PURE_PURSUIT_FINAL_DECEL_DISTANCE_M = 0.30
DEFAULT_PURE_PURSUIT_SPEED_PROFILE = SPEED_PROFILE_FIXED
DEFAULT_PURE_PURSUIT_FORWARD_CONTROL = FORWARD_CONTROL_TARGET_BEARING
DEFAULT_PURE_PURSUIT_PATH_PROFILE_SCHEDULING = PATH_PROFILE_SCHEDULING_OFF
DEFAULT_PURE_PURSUIT_PATH_PROFILE_STRAIGHT_SPEED_MPS = (
    DEFAULT_PURE_PURSUIT_LINEAR_SPEED_MPS
)
DEFAULT_PURE_PURSUIT_ROUTE_HEADING_BLEND = 0.45
DEFAULT_PURE_PURSUIT_CROSS_TRACK_GAIN = 0.4
DEFAULT_PURE_PURSUIT_CROSS_TRACK_SPEED_FLOOR_MPS = 0.04
DEFAULT_PURE_PURSUIT_MAX_CROSS_TRACK_CORRECTION_DEG = 15.0
DEFAULT_PURE_PURSUIT_ANGULAR_FEASIBILITY_SPEED_LIMIT = "on"
DEFAULT_PURE_PURSUIT_ANGULAR_FEASIBILITY_MARGIN = 0.85
DEFAULT_PURE_PURSUIT_MAX_LATERAL_ACCEL_MPS2 = 0.04
DEFAULT_PURE_PURSUIT_TURN_SPEED_MARGIN = 0.85
DEFAULT_PURE_PURSUIT_ROTATE_START_HEADING_ERROR_DEG = 75.0
DEFAULT_PURE_PURSUIT_ROTATE_STOP_HEADING_ERROR_DEG = 35.0
DEFAULT_PURE_PURSUIT_ROUTE_HEADING_ROTATE_START_DEG = 75.0
DEFAULT_PURE_PURSUIT_ROUTE_HEADING_ROTATE_STOP_DEG = 30.0
DEFAULT_PURE_PURSUIT_MAX_TRACK_ANGULAR_SPEED_RADPS = 0.09
DEFAULT_PURE_PURSUIT_HEADING_DEADBAND_DEG = 4.0
DEFAULT_PURE_PURSUIT_LATERAL_DEADBAND_M = 0.03
DEFAULT_PURE_PURSUIT_CURVATURE_LIMIT_START_HEADING_ERROR_DEG = 12.0
DEFAULT_PURE_PURSUIT_CURVATURE_LIMIT_FULL_HEADING_ERROR_DEG = 30.0
DEFAULT_PURE_PURSUIT_CROSS_TRACK_WARNING_M = 0.15
DEFAULT_PURE_PURSUIT_MAX_CROSS_TRACK_ERROR_M = 0.25
DEFAULT_TRACKING_ENDPOINT_TOLERANCE_M = 0.10
DEFAULT_TRACKING_START_TOLERANCE_M = 0.20
DEFAULT_TRACKING_MAX_SEGMENT_M = 0.30
DEFAULT_ODOM_FRAME = "odom"
DEFAULT_SCAN_HALF_ANGLE_DEG = 35.0
DEFAULT_HARD_STOP_RANGE_M = 0.16
DEFAULT_MIN_SCAN_RANGE_M = 0.40
DEFAULT_ROTATION_STOP_RANGE_M = 0.18
FORWARD_SOFT_STOP_MIN_CLOSE_RANGES = 2
DEFAULT_MAX_POSE_AGE_SEC = 10.0
DEFAULT_MAX_SCAN_AGE_SEC = 8.0
DEFAULT_MAX_AMCL_AGE_SEC = 15.0
DEFAULT_MAX_AMCL_VAR_X = 0.05
DEFAULT_MAX_AMCL_VAR_Y = 0.05
DEFAULT_MAX_AMCL_VAR_YAW = 0.10
DEFAULT_MAX_WAYPOINT_TIME_SEC = 180.0
DEFAULT_MAX_TF_UPDATE_GAP_SEC = 5.0
DEFAULT_TF_RECOVERY_TIME_SEC = 5.0
DEFAULT_LOCALIZATION_RECOVERY_TIME_SEC = 5.0
DEFAULT_CONTROL_RATE_HZ = 20.0
DEFAULT_SETTLE_SEC = 0.5
DEFAULT_REPLAN_TIMEOUT_SEC = 5.0
DEFAULT_MAX_REPLAN_SCAN_AGE_SEC = 1.0
DEFAULT_MAX_REPLAN_TF_AGE_SEC = 1.0
DEFAULT_OBSTACLE_FORWARD_DISTANCE_M = 0.75
DEFAULT_OBSTACLE_FORWARD_HALF_WIDTH_M = 0.25
DEFAULT_OBSTACLE_ANGLE_WINDOW_DEG = 45.0
DEFAULT_OBSTACLE_MIN_RANGE_M = 0.12
DEFAULT_ROBOT_FOOTPRINT_RADIUS_M = 0.10
DEFAULT_OBSTACLE_MIN_CLUSTER_SIZE = 3
DEFAULT_OBSTACLE_MIN_CLUSTER_WIDTH_M = 0.05
DEFAULT_OBSTACLE_INFLATE_RADIUS_M = 0.15
DEFAULT_MAX_START_SNAP_M = 0.20
DEFAULT_MAX_GOAL_SNAP_M = 0.30
DEFAULT_MAX_REPLAN_PATH_LENGTH_RATIO = 3.0
DEFAULT_RUN_LOCAL_MAP_INITIAL_SCAN_MODE = "forward"
DEFAULT_RUN_LOCAL_MAP_INITIAL_SCAN_COUNT = 5
DEFAULT_RUN_LOCAL_MAP_UPDATE_MODE = "forward"
DEFAULT_RUN_LOCAL_MAP_MIN_HIT_COUNT = 2
DEFAULT_RUN_LOCAL_MAP_INFLATION_RADIUS_M = DEFAULT_OBSTACLE_INFLATE_RADIUS_M
DEFAULT_RUN_LOCAL_MAP_MAX_TF_AGE_SEC = 1.0
DEFAULT_RUN_LOCAL_MAP_MAX_SCAN_AGE_SEC = 1.0
DEFAULT_RUN_LOCAL_MAP_MIN_USED_POINTS = 3
DEFAULT_RUN_LOCAL_MAP_MAX_REJECTED_RATIO = 0.90
DEFAULT_RUN_LOCAL_MAP_CORRIDOR_CHECK_DISTANCE_M = 0.75
DEFAULT_RUN_LOCAL_MAP_CLEARANCE_MARGIN_M = 0.04
DEFAULT_RUN_LOCAL_MAP_MAX_UPDATES = 3
DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_COUNT = 2
DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_FORWARD_HALF_WIDTH_M = 0.40
DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_ANGLE_WINDOW_DEG = 75.0
DEFAULT_RUN_LOCAL_MAP_SPARSE_RETRY_FORWARD_DISTANCE_M = 1.00
DEFAULT_RUN_LOCAL_MAP_PRUNE_BEHIND_DISTANCE_M = 0.20

DEFAULT_STARTUP_TIMEOUT_SEC = 20.0
STOP_PUBLISH_COUNT = 10
STOP_PUBLISH_HZ = 10.0
