#!/usr/bin/env python3
"""Compatibility facade for arena-active localization helpers."""

from arena_active_spin_core.active_explore_policy import (
    ActiveExplorePolicy,
    candidate_cluster_centroid,
    candidate_has_safe_shadow_approach_clearance,
    candidate_is_accepted_open_corridor,
    candidate_is_accepted_shadow_frontier,
    candidate_is_localization_pose_candidate,
    candidate_is_moving_shadow_frontier,
    candidate_path_min_clearance_m,
    candidate_path_needs_motion,
    candidate_path_start_point,
    candidate_path_unknown_ratio,
    candidate_target_point,
    candidate_visible_shadow_count,
)
from arena_active_spin_core.curve_following import (
    active_explore_curve_execution_record,
    active_explore_curve_path,
    pure_pursuit_curve_command,
    select_curve_lookahead_target,
    truncate_polyline_by_distance,
)
from arena_active_spin_core.diagnostics import (
    active_explore_config_from_arena_config,
    config_diagnostics,
    effective_recovery_mode,
    initial_diagnostics,
    json_safe,
    spin_diagnostics_template,
    update_safety_minima,
    write_diagnostics_json,
)
from arena_active_spin_core.explore_mission import (
    EXPLORE_ACTION_COMPLETE,
    EXPLORE_ACTION_CONFIRM_SHADOW_MAP,
    EXPLORE_ACTION_DRIVE_CANDIDATE,
    EXPLORE_ACTION_FAIL,
    EXPLORE_ACTION_RUN_LOCALIZATION_SPIN,
    EXPLORE_PHASE_COMPLETE,
    EXPLORE_PHASE_FAILED,
    EXPLORE_PHASE_HEATER_APPROACH,
    EXPLORE_PHASE_LOCALIZATION_SPIN,
    EXPLORE_PHASE_SHADOW_CONFIRM,
    EXPLORE_PHASE_SHADOW_MAPPING,
    ExploreMissionController,
    ExploreMissionDecision,
    ExploreMissionMotionResult,
    shadow_map_status,
)
from arena_active_spin_core.math_utils import (
    clamp,
    distance_2d,
    finite_point_2d,
    normalize_angle_rad,
    shortest_angle_delta_rad,
)
from arena_active_spin_core.models import (
    ACTIVE_EXPLORE_FRONTIER_CLUSTER_MATCH_M,
    ACTIVE_EXPLORE_FRONTIER_REACHED_PATH_M,
    ACTIVE_EXPLORE_FRONTIER_TARGET_MATCH_M,
    ACTIVE_EXPLORE_FRONTIER_UNREACHABLE_REASONS,
    ACTIVE_EXPLORE_LOCALIZATION_CANDIDATE_KINDS,
    ACTIVE_EXPLORE_PHASE_LOCALIZATION_POSE,
    ACTIVE_EXPLORE_PHASE_LOCALIZATION_SPIN,
    ACTIVE_EXPLORE_PHASE_SHADOW,
    ACTIVE_EXPLORE_SHADOW_APPROACH_GOAL_DRIFT_TOLERANCE_M,
    ACTIVE_EXPLORE_SHADOW_APPROACH_MIN_PATH_CLEARANCE_M,
    ACTIVE_EXPLORE_SHADOW_EMPTY_REPLANS_TO_COMPLETE,
    DEFAULT_STOP_COUNT,
    DEFAULT_STOP_HZ,
    LOCALIZER_FILTER_MAX_WALL_THICKNESS_M,
    LOCALIZER_FILTER_MIN_WALL_ASPECT_RATIO,
    LOCALIZER_FILTER_MIN_WALL_LENGTH_M,
    LOCALIZER_FILTER_WALL_EXPAND_CELLS,
    LOCALIZER_FILTER_WALL_MARGIN_CELLS,
    ActiveExploreMotionError,
    ArenaActiveSpinConfig,
    ArenaActiveSpinResult,
    CenterRepositionAction,
    CenterRepositionStep,
    PosePrior,
    SectorClearance,
)
from arena_active_spin_core.reposition import (
    candidate_heater_score,
    candidate_profile_valid,
    candidate_range,
    choose_center_reposition_action,
    choose_heater_approach_reposition_action,
    opposite_axis_side,
    short_wall_ranges_and_error,
)
from arena_active_spin_core.scan_safety import (
    angle_in_sector,
    covariance_list_from_localizer,
    dynamic_lateral_heading_from_scan,
    evaluate_clearance,
    evaluate_reposition_clearance,
    min_sector_range,
    min_valid_scan_range,
    odom_pose_from_msg,
    pose_prior_from_localizer_result,
    scan_sample_from_msg,
    valid_range,
    yaw_from_quaternion,
)
from arena_active_spin_core.session import (
    ArenaActiveSpinSession,
    run_arena_active_spin,
    stop_repeatedly,
)
from arena_active_spin_core.temporary_map import (
    blocked_cells_from_grid,
    cell_bounds,
    cluster_cells_8,
    cluster_is_wall_like,
    expand_cells,
    filter_scan_samples_with_temporary_obstacle_map,
    neighbors_8_cells,
    occupied_cells_from_grid,
    scan_endpoint_world,
    temporary_grid_localizer_obstacle_mask,
    temporary_map_cell_to_occupancy,
    temporary_map_occupancy_data,
    valid_scan_range_count,
)

__all__ = [name for name in globals() if not name.startswith("_")]
