from .analysis import build_analysis_model
from .cli import main, parse_args
from .constants import (
    CHI2_95_2D,
    DEFAULT_STEP_DISTANCE_M,
    NEAR_SINGULAR_COND,
    NEAR_SINGULAR_DET,
    REAL_ENDPOINT_COLUMNS,
    SIM_ENDPOINT_COLUMNS,
)
from .csv_data import (
    extract_points,
    extract_yaws,
    filter_latest_rows,
    filter_rows_by_run_range,
    finite_float,
    parse_run_number,
    parse_run_range,
    read_csv_rows,
    require_columns,
    run_ids,
    skip_record,
    valid_rows_with_columns,
)
from .errors import DataError
from .fallback_png import (
    draw_circle,
    draw_line,
    ellipse_sample_points,
    plot_transform,
    write_fallback_plot,
    write_png,
)
from .geometry import (
    local_displacements,
    mat_add,
    mat_mul,
    mat_scale,
    mat_transpose,
    mat_vec,
    motion_errors,
    normalize_angle_deg,
    rotation_matrix,
    vec_add,
    vec_scale,
    vec_sub,
)
from .output import format_matrix, print_report, write_json, write_summary_csv
from .plots import plot_scatter_with_ellipse, plot_sim_vs_real_errors
from .statistics import (
    as_points,
    circular_yaw_summary_deg,
    covariance_warning,
    determinant_2x2,
    eigenvector_for_value,
    ellipse_parameters,
    empirical_mean_cov,
    mahalanobis_squared,
    matrix_std,
    outlier_records,
    pseudo_inverse_symmetric_2x2,
    symmetric_eigen_2x2,
)

__all__ = [
    "CHI2_95_2D",
    "DEFAULT_STEP_DISTANCE_M",
    "NEAR_SINGULAR_COND",
    "NEAR_SINGULAR_DET",
    "REAL_ENDPOINT_COLUMNS",
    "SIM_ENDPOINT_COLUMNS",
    "DataError",
    "parse_run_number",
    "parse_run_range",
    "read_csv_rows",
    "require_columns",
    "filter_rows_by_run_range",
    "filter_latest_rows",
    "finite_float",
    "valid_rows_with_columns",
    "skip_record",
    "extract_points",
    "extract_yaws",
    "rotation_matrix",
    "mat_vec",
    "mat_mul",
    "mat_transpose",
    "mat_add",
    "mat_scale",
    "vec_add",
    "vec_sub",
    "vec_scale",
    "local_displacements",
    "motion_errors",
    "empirical_mean_cov",
    "as_points",
    "circular_yaw_summary_deg",
    "normalize_angle_deg",
    "symmetric_eigen_2x2",
    "eigenvector_for_value",
    "covariance_warning",
    "determinant_2x2",
    "pseudo_inverse_symmetric_2x2",
    "mahalanobis_squared",
    "outlier_records",
    "ellipse_parameters",
    "build_analysis_model",
    "matrix_std",
    "run_ids",
    "write_json",
    "write_summary_csv",
    "plot_scatter_with_ellipse",
    "plot_sim_vs_real_errors",
    "write_fallback_plot",
    "ellipse_sample_points",
    "plot_transform",
    "draw_circle",
    "draw_line",
    "write_png",
    "print_report",
    "format_matrix",
    "parse_args",
    "main",
]
