"""Compatibility exports for passive real-camera observer provenance."""

from scripts.aufgabe04.artifacts.backside_axis_observation import (
    BACKSIDE_AXIS_OBSERVATION_KIND,
    BACKSIDE_AXIS_OBSERVATION_SCHEMA_VERSION,
    BACKSIDE_AXIS_SAMPLE_SOURCE,
    BACKSIDE_CLASSIFICATION_BASIS,
    BACKSIDE_MODEL_EVIDENCE_STATE,
    BACKSIDE_VISIBLE_FACE,
    MAXIMUM_HEAD_CENTER_ERROR_RATIO,
    MAXIMUM_REGISTRATION_BEARING_DELTA_RAD,
    MAXIMUM_REGISTRATION_HEAD_CENTER_OFFSET_RATIO,
    PASSIVE_VIEWPOINT_OBSERVER_VERSION,
    REGISTERED_BACKSIDE_AXIS_SAMPLE_SOURCE,
    TARGET_REGISTRATION_LIDAR_SOURCE_CAMERA,
    TARGET_REGISTRATION_LIDAR_SOURCE_MAP,
    TARGET_REGISTRATION_MODE_BOUNDED_CAMERA_LIDAR,
    TARGET_REGISTRATION_MODE_MAP_PROJECTION,
)


__all__ = [
    "BACKSIDE_AXIS_OBSERVATION_KIND",
    "BACKSIDE_AXIS_OBSERVATION_SCHEMA_VERSION",
    "BACKSIDE_AXIS_SAMPLE_SOURCE",
    "BACKSIDE_CLASSIFICATION_BASIS",
    "BACKSIDE_MODEL_EVIDENCE_STATE",
    "BACKSIDE_VISIBLE_FACE",
    "MAXIMUM_HEAD_CENTER_ERROR_RATIO",
    "MAXIMUM_REGISTRATION_BEARING_DELTA_RAD",
    "MAXIMUM_REGISTRATION_HEAD_CENTER_OFFSET_RATIO",
    "PASSIVE_VIEWPOINT_OBSERVER_VERSION",
    "REGISTERED_BACKSIDE_AXIS_SAMPLE_SOURCE",
    "TARGET_REGISTRATION_LIDAR_SOURCE_CAMERA",
    "TARGET_REGISTRATION_LIDAR_SOURCE_MAP",
    "TARGET_REGISTRATION_MODE_BOUNDED_CAMERA_LIDAR",
    "TARGET_REGISTRATION_MODE_MAP_PROJECTION",
]
